[package]
name = "rust-tc-sdk"
version = "0.1.0"
license = "ISC"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.33.0", features = ["full"] }
tokio-util = "0"
lazy_static = "1.4.0"
error-chain = "0.12.4"
r2d2 = "0"
state = "0"

futures = "0.3.28"
async-trait = "0.1.74"

diesel = { version = "2.1.3", features = ["sqlite", "r2d2", "libsqlite3-sys", "chrono", "serde_json", "uuid"] }
libsqlite3-sys = { version = "0", features = ["bundled"] }

serde = "1.0.189"
serde_json = "1.0.107"

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]

[dependencies.libp2p]
version = "0.52.4"
features = [
  "full"
]

[dependencies.uuid]
version = "1.5.0"
features = [
  "v4", # Lets you generate random UUIDs
  "fast-rng", # Use a faster (but still sufficiently random) RNG
  "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
