[package]
name = "rust-tc-sdk"
version = "0.1.0"
license = "ISC"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
error-chain = "0.12.4"
r2d2 = "0"
state = "0"
rand = { version = "0.8.5", features = ["serde", "default"] }

libp2p-webrtc = { version = "0.6.1-alpha", features = ["tokio"] }
log = "0.4.20"
env_logger = "0.10.0"

futures = "0.3.28"
async-trait = "0.1.74"

diesel = { version = "2.1.3", features = ["sqlite", "r2d2", "libsqlite3-sys", "chrono", "serde_json", "uuid"] }
diesel_migrations = "2.1.0"
libsqlite3-sys = { version = "0", features = ["bundled"] }

serde = "1.0.189"
serde_json = "1.0.107"
neon-serde3 = "0.10.0"

getset = "0.1.2"
derive_more = "0.99.11"
dirs = "5.0.1"

[dependencies.neon]
version = "0.10.1"
default-features = false
features = ["napi-6"]

[dependencies.libp2p]
version = "0.52.4"
features = [
    "full"
]

[dependencies.uuid]
version = "1.5.0"
features = [
    "v4", # Lets you generate random UUIDs
    "fast-rng", # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
