[package]
name = "rust-tc-sdk"
version = "0.1.0"
license = "ISC"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
error-chain = "0.12.4"
r2d2 = "0"
state = "0"

log = "0.4.20"
env_logger = "0.11.1"

tokio = { version = "1", features = ["full"] }

diesel = { version = "2.1.3", features = ["sqlite", "r2d2", "libsqlite3-sys", "chrono", "serde_json", "uuid"] }
diesel_migrations = "2.1.0"
tokio-diesel = "0"
libsqlite3-sys = { version = "0", features = ["bundled"] }

serde = "1"
serde_json = "1"
neon-serde3 = "0"

getset = "0"
derive_more = "0.99.11"
dirs = "5.0.1"

[dependencies.neon]
version = "0.10.1"
default-features = false
features = ["napi-latest", "promise-api", "channel-api", "neon-macros", "proc-macros"]

[dependencies.libp2p]
version = "0.53.2"
features = [
    "noise",
    "mdns",
    "tcp",
    "websocket",
    "yamux",
    "ecdsa",
    "tls",
    "dns",
    "gossipsub",
    "ping",
    "identify",
    "relay",
    "serde",
    "macros",
    "rendezvous",
    "tokio"
]

[dependencies.uuid]
version = "1"
features = [
    "v4", "v5", "v6", # Lets you generate random UUIDs
    "fast-rng", # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
